book_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('users/', include('users.urls')),
]

notes/urls.py
"""Defines URL patterns for notes app."""

from django.urls import path

from . import views

app_name = 'notes'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Show all books
    path('books/', views.books, name='books'),

    # Show chapters for a single book.
    path('books/<int:book_id>/', views.book, name='book'),

    # Show notes for a chapter.
    path('books/<int:book_id>/<int:chapter_id>/', views.chapter, name='chapter'),

    # Page for adding a new book.
    path('new_book/', views.new_book, name='new_book'),
]

users/urls.py
"""Defines URL patterns for users app."""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    # Login page.
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    # Logout page.
    path('logout/', views.logout_view, name='logout'),

    # Registration page.
    path('register/', views.register, name='register'),
]

notes/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    """A book the user is reading."""
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the title."""
        return self.title

class Chapter(models.Model):
    """A chapter in the book."""
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the chapter title."""
        return self.chapter_title

class Note(models.Model):
    """A note about a chapter."""
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the note."""
        return self.text

users/models.py
from django.db import models

# Create your models here.

notes/forms.py
from django import forms

from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title']
        labels = {'title': ''}

notes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Book, Chapter
from .forms import BookForm

# Create your views here.
def index(request):
    """Return the home page for Notes."""
    return render(request, 'notes/index.html')

def books(request):
    """Return all books."""
    books = Book.objects.order_by('date_added')
    context = {'books': books}
    return render(request, 'notes/books.html', context)

def book(request, book_id):
    """Return chapters related to a single book."""
    book = Book.objects.get(id=book_id)
    chapters = book.chapter_set.order_by('id')
    context = {'book': book, 'chapters': chapters}
    return render(request, 'notes/book.html', context)

def chapter(request, book_id, chapter_id):
    """Return notes related to a chapter."""
    book = Book.objects.get(id=book_id)
    chapter = Chapter.objects.get(id=chapter_id)
    notes = chapter.note_set.order_by('id')
    context = {'book': book, 'chapter': chapter, 'notes': notes}
    return render(request, 'notes/note.html', context)

def new_book(request):
    """Add a new book."""
    if request.method != 'POST':
        # No data submitted; create blank form.
        form = BookForm()
    else:
        # POST data submitted; process data.
        form = BookForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('notes:books'))

    context = {'form': form}
    return render(request, 'notes/new_book.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('notes:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display empty registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in, then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('notes:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

notes/templates/notes/base.html
<p>
    <a href="{% url 'notes:index' %}">Book Notes</a> - 
    <a href="{% url 'notes:books' %}">Books</a> - 
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:login' %}">log in</a> - 
        <a href="{% url 'users:register' %}">register</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

notes/templates/notes/book.html
{% extends "notes/base.html" %}

{% block content %}

    <h1>{{ book }}</h1>

    <ul>
        {% for chapter in chapters %}
            <li>
                <h3>
                    <a href="{% url 'notes:chapter' book.id chapter.id %}">{{ chapter }}</a>
                </h3>
            </li>
        {% empty %}
            <li>No chapters have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

notes/templates/notes/books.html
{% extends "notes/base.html" %}

{% block content %}

    <p>Books</p>

    <ul>
        {% for book in books %}
            <li>
                <a href="{% url 'notes:book' book.id %}">{{ book }}</a>
            </li>
        {% empty %}
            <li>No books have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'notes:new_book' %}">Add a new book:</a>

{% endblock content %}

notes/templates/notes/index.html
{% extends "notes/base.html" %}

{% block content %}
    <p>Book Notes allows you to keep notes on a book you are reading, with the aim of making sure you are thinking about the material as you read, and allowing you to quickly recap what you took away from a book you've read in the past.</p>
{% endblock content %}

notes/templates/notes/new_book.html
{% extends "notes/base.html" %}

{% block content %}

    <p>Add a new book:</p>

    <form action="{% url 'notes:new_book' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add book</button>
    </form>

{% endblock content %}

notes/templates/notes/note.html
{% extends "notes/base.html" %}

{% block content %}

    <h1>{{ book }}</h1>
    <h2>{{ chapter }}</h2>

    <ul>
        {% for note in notes %}
            <li>
                {{ note }}
            </li>
        {% empty %}
            <li>No notes have been added yet.</li>
        {% endfor %}
    </ul>

{% endblock content %}

users/templates/users/login.html
{% extends "notes/base.html" %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">log in</button>

        <input type="hidden" name="next" value="{% url 'notes:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "notes/base.html" %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">register</button>

        <input type="hidden" name="next" value="{% url 'notes:index' %}" />
    </form>

{% endblock content %}